# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/muxctrl.xdc

# IP: ip/MUX4T1_5_0/MUX4T1_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MUX4T1_5_0 || ORIG_REF_NAME==MUX4T1_5_0} -quiet] -quiet

# IP: ip/Constant_5b1_0/Constant_5b1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Constant_5b1_0 || ORIG_REF_NAME==Constant_5b1_0} -quiet] -quiet

# IP: ip/Constant_5b0_0/Constant_5b0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Constant_5b0_0 || ORIG_REF_NAME==Constant_5b0_0} -quiet] -quiet

# IP: ip/Slice_8T5_1/Slice_8T5_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Slice_8T5_1 || ORIG_REF_NAME==Slice_8T5_1} -quiet] -quiet

# IP: ip/Slice_8T5_0/Slice_8T5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Slice_8T5_0 || ORIG_REF_NAME==Slice_8T5_0} -quiet] -quiet

# IP: ip/MUX8T1_8_0/MUX8T1_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MUX8T1_8_0 || ORIG_REF_NAME==MUX8T1_8_0} -quiet] -quiet

# IP: ip/Constant_8b1_0/Constant_8b1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Constant_8b1_0 || ORIG_REF_NAME==Constant_8b1_0} -quiet] -quiet

# IP: ip/Concat_1/Concat_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Concat_1 || ORIG_REF_NAME==Concat_1} -quiet] -quiet

# IP: ip/Concat_0/Concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Concat_0 || ORIG_REF_NAME==Concat_0} -quiet] -quiet

# IP: ip/Slice_5T4_1/Slice_5T4_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Slice_5T4_1 || ORIG_REF_NAME==Slice_5T4_1} -quiet] -quiet

# IP: ip/Slice_5T4_0/Slice_5T4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Slice_5T4_0 || ORIG_REF_NAME==Slice_5T4_0} -quiet] -quiet

# IP: ip/MUX2T1_5_1/MUX2T1_5_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MUX2T1_5_1 || ORIG_REF_NAME==MUX2T1_5_1} -quiet] -quiet

# IP: ip/MUX2T1_5_0/MUX2T1_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MUX2T1_5_0 || ORIG_REF_NAME==MUX2T1_5_0} -quiet] -quiet

# IP: ip/Constant_1b1_0/Constant_1b1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Constant_1b1_0 || ORIG_REF_NAME==Constant_1b1_0} -quiet] -quiet
