# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado_Labs/RAM/RAM.srcs/sources_1/ip/RAM_D/RAM_D.xci
# IP: The module: 'RAM_D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Labs/RAM/RAM.gen/sources_1/ip/RAM_D/RAM_D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_D'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Vivado_Labs/RAM/RAM.srcs/sources_1/ip/RAM_D/RAM_D.xci
# IP: The module: 'RAM_D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Labs/RAM/RAM.gen/sources_1/ip/RAM_D/RAM_D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_D'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
