# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/Regs_0/Regs_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Regs_0 || ORIG_REF_NAME==Regs_0} -quiet] -quiet
