# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pre/A7.xdc

# IP: ip/VGA_0/VGA_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VGA_0 || ORIG_REF_NAME==VGA_0} -quiet] -quiet

# IP: ip/Seg7_Dev_0/Seg7_Dev_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Seg7_Dev_0 || ORIG_REF_NAME==Seg7_Dev_0} -quiet] -quiet

# IP: ip/ROM_D_0/ROM_D_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM_D_0 || ORIG_REF_NAME==ROM_D_0} -quiet] -quiet

# IP: ip/RAM_B/RAM_B.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM_B || ORIG_REF_NAME==RAM_B} -quiet] -quiet

# IP: ip/mySCPU_exp/mySCPU_exp.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mySCPU_exp || ORIG_REF_NAME==mySCPU_exp} -quiet] -quiet

# IP: d:/Vivado_Labs/Lab4_mySCPUexp/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/mySCPU_exp/src/Regs_0/Regs_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Regs_0 || ORIG_REF_NAME==Regs_0} -quiet] -quiet

# IP: d:/Vivado_Labs/Lab4_mySCPUexp/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/mySCPU_exp/src/MUX2T1/MUX2T1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MUX2T1 || ORIG_REF_NAME==MUX2T1} -quiet] -quiet

# IP: d:/Vivado_Labs/Lab4_mySCPUexp/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/mySCPU_exp/src/MUX4T1/MUX4T1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MUX4T1 || ORIG_REF_NAME==MUX4T1} -quiet] -quiet

# XDC: d:/Vivado_Labs/Lab4_mySCPUexp/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/ROM_D_0/ROM_D_0_ooc.xdc

# XDC: d:/Vivado_Labs/Lab4_mySCPUexp/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/RAM_B/RAM_B_ooc.xdc
